"""Redraw of Classification-Performance-Measures_6: PR-curve comparison.

Two Precision-Recall (PR) curves A and B used to illustrate that the PR
curve can serve as a model / algorithm / hyper-parameter selection metric:
the *outer* curve B (closer to the top-right corner) is better than the
*inner* curve A, because every (precision, recall) point on B dominates the
corresponding point on A.

NOTE on the axes: this figure follows the original's unconventional layout
where the x-axis is Precision and the y-axis is Recall (opposite to the
sklearn habit of recall-on-x). Both curves start near the top-left
(Precision ~ 0, Recall ~ 1) and descend to the bottom-right
(Precision ~ 1, Recall ~ 0).

The curves are purely illustrative (synthetic), generated by the power-law
family   recall = (1 - precision**k)**(1/k)  ,  precision = t,
with B using a larger k so it bulges further toward the top-right and fully
envelops A.

Style: the original is a clean hand-drawn black/white sketch -- thin black
lines, hidden top/right spines, arrow-headed axes, only 0 and 1 marked on
the axes, large hand-written-ish A / B labels, and faint gray dotted
reference lines at Precision = 1 and Recall = 1. We keep that look while
applying the shared _style fonts/background.
"""

import sys

sys.path.insert(0, "/Users/mux/code_workspace/PlayML/theoretical_part/pngs_redrawn/")

import numpy as np

import _style

OUT_PATH = (
    "/Users/mux/code_workspace/PlayML/theoretical_part/pngs_redrawn/"
    "Classification-Performance-Measures_6.png"
)

CURVE_COLOR = "#1A1A1A"   # near-black thin lines, matching the sketch
AXIS_COLOR = "#1A1A1A"
REF_COLOR = "#9A9A9A"     # faint gray dotted reference lines


def pr_curve(k, n=400):
    """Synthetic PR curve from the power-law family.

    precision = t in [0, 1], recall = (1 - t**k)**(1/k). Larger k bulges
    the curve further toward the top-right corner (a "better" model).
    """
    precision = np.linspace(0.0, 1.0, n)
    recall = (1.0 - precision ** k) ** (1.0 / k)
    return precision, recall


def main():
    fig, ax = _style.new_ax(figsize=(6.6, 5.0))

    # No background grid for this clean sketch look.
    ax.grid(False)

    # --- The two PR curves (A inner, B outer) -----------------------------
    pa, ra = pr_curve(k=1.7)   # inner curve A (smaller k -> less bulged)
    pb, rb = pr_curve(k=3.2)   # outer curve B (larger k -> bulges outward)

    ax.plot(pa, ra, color=CURVE_COLOR, linewidth=1.4, zorder=3)
    ax.plot(pb, rb, color=CURVE_COLOR, linewidth=1.4, zorder=3)

    # --- Curve labels A and B (large, placed along each curve) ------------
    # A: mid-section of the inner curve.
    ia = int(0.42 * len(pa))
    ax.text(
        pa[ia] + 0.02,
        ra[ia] - 0.07,
        "A",
        color=CURVE_COLOR,
        fontsize=26,
        fontstyle="italic",
        ha="left",
        va="top",
        zorder=4,
    )
    # B: upper-right section of the outer curve.
    ib = int(0.60 * len(pb))
    ax.text(
        pb[ib] + 0.015,
        rb[ib] + 0.04,
        "B",
        color=CURVE_COLOR,
        fontsize=26,
        fontstyle="italic",
        ha="left",
        va="bottom",
        zorder=4,
    )

    # --- Faint gray dotted reference lines at Precision = 1 and Recall = 1 -
    ax.axvline(1.0, color=REF_COLOR, linestyle=":", linewidth=1.3, zorder=1)
    ax.axhline(1.0, color=REF_COLOR, linestyle=":", linewidth=1.3, zorder=1)

    # --- Arrow-headed axes (hand-drawn sketch style) ----------------------
    # Hide all default spines and ticks; we draw our own axis arrows.
    for side in ("top", "right", "bottom", "left"):
        ax.spines[side].set_visible(False)
    ax.set_xticks([])
    ax.set_yticks([])

    arrow_kw = dict(
        arrowstyle="-|>",
        color=AXIS_COLOR,
        linewidth=1.6,
        mutation_scale=18,
        shrinkA=0,
        shrinkB=0,
    )
    # x-axis (Precision): from origin to the right, with arrow head.
    ax.annotate("", xy=(1.12, 0.0), xytext=(0.0, 0.0), arrowprops=arrow_kw, zorder=2)
    # y-axis (Recall): from origin upward, with arrow head.
    ax.annotate("", xy=(0.0, 1.12), xytext=(0.0, 0.0), arrowprops=arrow_kw, zorder=2)

    # --- Axis tick labels: only 0 (origin) and 1 (top of y-axis) ----------
    ax.text(-0.045, -0.055, "0", color=AXIS_COLOR, fontsize=18,
            ha="right", va="top", zorder=4)
    ax.text(-0.045, 1.0, "1", color=AXIS_COLOR, fontsize=18,
            ha="right", va="center", zorder=4)

    # --- Axis names: Precision (x) and Recall (y) -------------------------
    ax.text(0.58, -0.10, "Precision", color=AXIS_COLOR, fontsize=18,
            ha="center", va="top", zorder=4)
    ax.text(-0.12, 0.55, "Recall", color=AXIS_COLOR, fontsize=18,
            ha="right", va="center", rotation=0, zorder=4)

    # --- Limits with margins so the arrow heads and labels are not clipped -
    ax.set_xlim(-0.22, 1.20)
    ax.set_ylim(-0.18, 1.20)
    ax.set_aspect("equal", adjustable="box")

    # finalize() would re-hide top/right spines (already hidden) and save.
    _style.finalize(fig, OUT_PATH)
    print("saved:", OUT_PATH)


if __name__ == "__main__":
    main()
