"""Redraw of Polynomial-Regression-and-Model-Generalization_4: "Best fit".

A "learning curve" for a degree-2 polynomial regression -- the model that is
just complex enough for data generated by ``y = 0.5*x^2 + x + 2 + noise``.
We synthesize 100 points (seed 666), split 75 train / 25 test
(random_state=10), then for i = 1..75 fit a Pipeline of
``PolynomialFeatures(2) + StandardScaler + LinearRegression`` on the first i
training samples and record train / test RMSE.

Because the model capacity matches the true relationship, the two curves
converge to a close, low band (train ~ 1.0, test ~ 1.2) with only a small
gap -- the signature of good generalization ("just right"). The y-axis is
capped at 4.0 so the few enormous early test errors run off the top of the
plot, exactly as in the original figure.

Style matches the unified _style.py (clean modern look, palette C0 blue for
train / C1 amber for test). Chinese axis labels are added for readability and
consistency with the rest of the set; the original English title "Best fit"
is kept.
"""

import sys

sys.path.insert(0, "/Users/mux/code_workspace/PlayML/theoretical_part/pngs_redrawn/")

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

import _style

OUT_PATH = "/Users/mux/code_workspace/PlayML/theoretical_part/pngs_redrawn/Polynomial-Regression-and-Model-Generalization_4.png"

TRAIN_COLOR = _style.PALETTE[0]  # blue  -> train
TEST_COLOR = _style.PALETTE[3]   # amber -> test (matches original C1-style orange)

Y_MAX = 4.0


def polynomial_regression(degree):
    """Pipeline: poly features -> standardize -> linear regression."""
    return Pipeline(
        [
            ("poly", PolynomialFeatures(degree=degree)),
            ("std_scaler", StandardScaler()),
            ("lin_reg", LinearRegression()),
        ]
    )


def build_dataset():
    """Synthesize the chp6 data and split into 75 train / 25 test."""
    np.random.seed(666)
    x = np.random.uniform(-3.0, 3.0, size=100)
    X = x.reshape(-1, 1)
    y = 0.5 * x**2 + x + 2.0 + np.random.normal(0, 1, size=100)
    return train_test_split(X, y, random_state=10)


def learning_curve(estimator, X_train, X_test, y_train, y_test):
    """Train on the first i samples (i=1..len), record train/test RMSE."""
    train_rmse, test_rmse = [], []
    for i in range(1, len(X_train) + 1):
        estimator.fit(X_train[:i], y_train[:i])

        y_train_pred = estimator.predict(X_train[:i])
        train_rmse.append(
            np.sqrt(mean_squared_error(y_train[:i], y_train_pred))
        )

        y_test_pred = estimator.predict(X_test)
        test_rmse.append(np.sqrt(mean_squared_error(y_test, y_test_pred)))

    return np.array(train_rmse), np.array(test_rmse)


def main():
    X_train, X_test, y_train, y_test = build_dataset()

    train_rmse, test_rmse = learning_curve(
        polynomial_regression(2), X_train, X_test, y_train, y_test
    )

    sizes = np.arange(1, len(X_train) + 1)

    fig, ax = _style.new_ax(figsize=(6.4, 4.8))

    ax.plot(sizes, train_rmse, color=TRAIN_COLOR, linewidth=2.0, label="train")
    ax.plot(sizes, test_rmse, color=TEST_COLOR, linewidth=2.0, label="test")

    # Fixed range: cap at 4.0 so the early huge test errors overflow the top,
    # which is the characteristic look of the original figure.
    ax.set_xlim(0, 76)
    ax.set_ylim(0, Y_MAX)
    ax.set_xticks(range(0, 71, 10))
    ax.set_yticks(np.arange(0, Y_MAX + 0.5, 0.5))

    # Highlight the converged "small-gap" band (train vs test) -- the point
    # of "best fit": good generalization, unlike the large gap of overfit.
    tail = slice(len(sizes) - 25, None)
    band_lo = float(train_rmse[tail].mean())
    band_hi = float(test_rmse[tail].mean())
    ax.axhspan(band_lo, band_hi, color="#94A3B8", alpha=0.18, zorder=0)
    ax.annotate(
        "收敛后 gap 很小\n(泛化良好)",
        xy=(60, (band_lo + band_hi) / 2),
        xytext=(38, 2.55),
        fontsize=10,
        ha="center",
        color="#334155",
        arrowprops=dict(arrowstyle="->", color="#64748B", lw=1.2),
    )

    ax.set_title("Best fit")
    ax.set_xlabel("训练样本数")
    ax.set_ylabel("RMSE 误差")
    ax.legend(loc="upper right")

    _style.finalize(fig, OUT_PATH)
    print("saved:", OUT_PATH)
    print(
        "train tail ~ %.3f, test tail ~ %.3f"
        % (train_rmse[tail].mean(), test_rmse[tail].mean())
    )


if __name__ == "__main__":
    main()
